apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecrets }}"
      containers:
      - args:
        - agent
        - -dev
        - -client=0.0.0.0
        - -bind=0.0.0.0
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/status/leader
            port: {{ .Values.service.ports.httpPort }}
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: {{ template "name" . }}
        ports:
        - containerPort: {{ .Values.service.ports.httpTargetPort }}
          protocol: TCP
        - containerPort: {{ .Values.service.ports.rcpTargetPort }}
          protocol: TCP
        - containerPort: {{ .Values.service.ports.serflanTcpTargetPort }}
          protocol: TCP
        - containerPort: {{ .Values.service.ports.serflanUdpTargetPort }}
          protocol: UDP
        - containerPort: {{ .Values.service.ports.serfwanTcpTargetPort }}
          protocol: TCP
        - containerPort: {{ .Values.service.ports.serfwanUdpTargetPort }}
          protocol: UDP
        - containerPort: {{ .Values.service.ports.serverTargetPort }}
          protocol: TCP
        - containerPort: {{ .Values.service.ports.consuldnsTargetPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/status/leader
            port: 8500
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

