{{- if .Values.cronautoscaling.enabled }}
apiVersion: autoscaling.alibabacloud.com/v1beta1
kind: CronHorizontalPodAutoscaler
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.app.name }}-chpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}
  jobs:
    {{- range $job := .Values.cronautoscaling.jobs }}
    - name: {{ $job.name }}
      schedule: {{ $job.schedule }}
      targetSize: {{ $job.targetSize }}
    {{- end }}
  {{- end }}
